# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c98f899a03bc33c08815df12c3adb3ac14df36046a0fbc1702428b33a69088b4b9f9289f624fc2391d5cf64880a709f54dc459e87fb9f7bb912298d4595423c

test:
  secret_key_base: 84a754704d00c7f74a3b5d9a5c0d7253d9fdd8af1f1db700a31f1b46f113ebaa67a58ccaff4fe7fcbea5e7fcfc16580e03c1ae7f0ea6582cd807a9226842e37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
